# Generated by Django 4.1.3 on 2022-12-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_player_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('-power',), 'verbose_name': 'игрок', 'verbose_name_plural': 'игроки'},
        ),
    ]
