# Generated by Django 4.1.3 on 2022-12-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_player_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('title',), 'verbose_name': 'команда', 'verbose_name_plural': 'команды'},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='team',
            new_name='teams',
        ),
    ]
