# Generated by Django 4.1.3 on 2022-12-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='администратор'),
        ),
    ]
